# Generated by Django 4.2.7 on 2023-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenresOfFavMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(max_length=200)),
                ('genre_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavMovies',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('poster_path', models.TextField()),
                ('overview', models.TextField()),
                ('runtime', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(to='movies.genresoffavmovies')),
            ],
        ),
    ]
